### ISSUE TITLE
Install error:

### ISSUE THREAD

**Issue by Kongledyret** [Bigjoos/U-232-V5#1]
Hi!

Seems like the installer when it´s importing .sql for php tracker has some issues. Fails to import .db to SQL. XBT .sql is ok though.

**Comment by whocares-openscene** [comment]
See either [this post on the support forums](https://forum-u-232.servebeer.com/index.php/topic,3801.0.html) or [This pull request](https://github.com/Bigjoos/U-232-V5/pull/6)

**Comment by Bigjoos** [comment]
Updates should have resolved all issues.
