### ISSUE TITLE
Password Hashing Method

### ISSUE THREAD

**Issue by HDVinnie** [Bigjoos/U-232-V5#100]
U232 uses a outdated password hashing method. https://github.com/Bigjoos/U-232-V5/blob/master/include/password_functions.php

Being on V5 already I am suggesting that this be a priority issue and that U232 goes with the standard PHP bcrypt method.

**Comment by PrinceKael** [comment]
Any update on this? Using MD5 is worrying in these times, bcrypt or an equivalent alternative would be better. Something like the below? I'm not a programmer though and suck at PHP.

```
function register($username, $pass) {
    $hash = password_hash($pass, PASSWORD_BCRYPT);
    save($username, $hash);
}
function login($username, $pass) {
$hash = password_hash($pass, PASSWORD_DEFAULT);
	if (password_verify($pass, $hash)) {
		echo "Success!"
	}
	else {
		echo "Login failed."
}
}
```

**Comment by HDVinnie** [comment]
@PrinceKael I wouldn't count on it. This issue was opened over 2 years ago and the devs couldn't even take the time to comment on it.
