### ISSUE TITLE
First account creation sends email confirmation but is not needed

### ISSUE THREAD

**Issue by sdelrio** [Bigjoos/U-232-V5#12]
When creating first account after installation `takesignup.php` sends e-mail confirmation when is not needed:

```
[...]
To confirm your user registration, you have to follow this link:

http://localhost:8080/confirm.php?id=1&secret=
[...]
```

The secret is empty, but really this mail is not needed since the first account created is already activated.

**Comment by Bigjoos** [comment]
No idea what your talking about, that was fixed days ago and i just tested it once again, it does not send out an email if its a sysop signup.

Sysop Account successfully activated!

Your account has been activated! However, it appears that you could not be logged in automatically. A possible reason is that you disabled cookies in your browser. You have to enable cookies to use your account. Please do that and then log in and try again.

**Comment by sdelrio** [comment]
I'll check again tomorrow after cloning from the repo on a clean installation.

What I check today, the message shows as you say on the browser after creating, and after that I can loging with the credentials. But the e-mail is sent anyway.

**Comment by sdelrio** [comment]
It happens from a fresh clean installation. I'll check the code and I'll make the pull request when I find it.

**Comment by sdelrio** [comment]
The sysop check if after the mail:

Last lines `takeinfo.php`(172-176):

``` php
if ($arr[0] || EMAIL_CONFIRM) 
mail($email, "{$INSTALLER09['site_name']} {$lang['takesignup_confirm']}", $body, "{$lang['takesignup_from']} {$INSTALLER09['site_email']}");
else 
logincookie($id, $wantpasshash);
header("Refresh: 0; url=ok.php?type=". (!$arr[0]? "sysop" : (EMAIL_CONFIRM ? "signup&email=" . urlencode($email) : "confirm")));
```

I think just  checking `$arr[0] > 0` before sending mail is enough. I'll make a PR with something like this:

``` php
// Change:
if ($arr[0] || EMAIL_CONFIRM) 
// To:
if ($arr[0] && EMAIL_CONFIRM) 
```

**Comment by Bigjoos** [comment]
Closed for now.
