### ISSUE TITLE
Anyone still here?

### ISSUE THREAD

**Issue by ShadoW69-KaGe69** [Bigjoos/U-232-V5#158]
Hey, guys.
I've been wondering, if you guys are still kicking?
Forum, IRC and everything is dead it seems.
Anyone still here lurking in the shadow?

**Comment by iseeyoucopy** [comment]
No isn't dead this source has been moved to  https://github.com/iseeyoucopy/U-232-Trinity-RC

Forums with all the posts and everything else
https://forum-u-232.duckdns.org/

Test site is https://u-232.duckdns.org/login.php?returnto=%2F

I have taken the forums and the source from Bigjoos and I will keep it alive and updated how much I can...

The latest version V6 I'm still working on it, but is working fine

**Comment by ShadoW69-KaGe69** [comment]
Hey mate,
The forum doesn't seem to be working for me.

**Comment by Bigjoos** [comment]
I’ve just never had the time to do anything. Glad Iseeyoucopy is still flying the flag tho. I’ll get a look and catch up soon!!

**Comment by iseeyoucopy** [comment]
> Hey mate, The forum doesn't seem to be working for me.
My mistake 


https://u-232-forum.duckdns.org/

**Comment by iseeyoucopy** [comment]
> I’ve just never had the time to do anything. Glad Iseeyoucopy is still flying the flag tho. I’ll get a look and catch up soon!!

I'm glad that I can keep this alive, people put they free time into this🤗🤗🤗

**Comment by ShadoW69-KaGe69** [comment]
I'm happy the bandwagon is still moving tho. I am so far out of  touch with the source code, it would take me a long time to catch up :)
