### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by ghost** [Bigjoos/U-232-V5#79]
When creating the second user, for the system bot, it fails because the users->passhint is missing a default value. If there are other table columns without defaults, they will fail when insert/update also,

I can't remember if this is a requirement of php7 or of mysql 5.7(possibly strict mode, which is default when installing Percona).

Thank you

**Comment by whocares-openscene** [comment]
U232-V5 is not compatible with MySQL 5.7 mostly for this reason.

**Comment by ghost** [comment]
Ok.
Thanks
